spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mamabike
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
  data:
    mongodb:
      uri: mongodb://localhost:27017/mamabike
redis:
  host: 127.0.0.1
  port: 6379
  max-idle: 5
  max-total: 10
  max-wait-millis: 3000

